### ISSUE TITLE
Amazing repo, but the README could use an update

### ISSUE THREAD

**Issue by yeamusic21** [yogeshwaran01/instagramy#11]
README seems pretty outdated.  I had to read the core code to figure out how to use the package.  

Here is just an example:

```
# Connecting the profile
 user = InstagramUser(uname, os.environ.get("INSTAGRAM_SESSIONID"))
# get user data
hls = user.user_data
# get high level stats such as followers, following, total_posts
followers, following, total_posts = hls['edge_followed_by']['count'], hls['edge_follow']['count'], hls["edge_owner_to_timeline_media"]["count"]
print("followers, following, total_posts = ", followers, following, total_posts)
```

**Comment by yogeshwaran01** [comment]
@yeamusic21 No,  `README` is not outdated

*Example 1*

```python
>>>  user = InstagramUser(uname, os.environ.get("INSTAGRAM_SESSIONID"))
>>> hls = user.user_data
>>> followers, following, total_posts = hls['edge_followed_by']['count'], hls['edge_follow']['count'], hls["edge_owner_to_timeline_media"]["count"]
>>> print("followers, following, total_posts = ", followers, following, total_posts)
```
*Example 2*

```python
>>> user = InstagramUser(uname, os.environ.get("INSTAGRAM_SESSIONID"))
>>> followers, following, total_posts = user.number_of_follwers, user.number_of_following, user.number_of_post
>>> print("followers, following, total_posts = ", followers, following, total_posts)
```

Both `Example 1` and `Example 2` return the same output. Some of the data of the user are loaded as `properties`. Only some properties are only mentioned in `README`. You can get all the  properties by

```python
>>>  user = InstagramUser(uname, os.environ.get("INSTAGRAM_SESSIONID"))
>>> dir(user)
>>> ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'biography', 'connected_fb_page', 'followed_by_viewer', 'follows_viewer', 'fullname', 'get_json', 'has_blocked_viewer', 'has_country_block', 'has_requested_viewer', 'is_blocked_by_viewer', 'is_joined_recently', 'is_private', 'is_verified', 'no_of_mutual_follower', 'number_of_followers', 'number_of_followings', 'number_of_posts', 'other_info', 'posts', 'posts_display_urls', 'profile_picture_url', 'requested_by_viewer', 'restricted_by_viewer', 'username', 'website']
```
Thank you,

**Comment by yeamusic21** [comment]
@yogeshwaran01 - First, thanks so much for the quick response!@  Love the quick response time on this.

Second, I love this package you developed.  Personally, I think Example 2 would be easier for people to follow.  In the README you're using `user.user_data` but as you pointed out, `user.number_of_follwers, user.number_of_following, user.number_of_post` is a much more intuitive way to grab the properties you've made available.  I'm just saying, maybe it's just me, but since the README is using `user.user_data`  it felt like it took me a bit longer to figure out how to get certain stats than it should (but maybe that's on me).  I leave this information to use at your own discretion.  I'll close out the issue now.  Thanks again :)

**Comment by yogeshwaran01** [comment]
Your  suggestion is right. I update the `README` soon.
