### ISSUE TITLE
KeyError: 'ProfilePage' error while using "InstagramUser"

### ISSUE THREAD

**Issue by NivedhaRamesh** [yogeshwaran01/instagramy#3]
facing error on running the following query:

"from instagramy import InstagramUser
user = InstagramUser("github")
user.number_of_followers"

Error:

---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/instagramy/InstagramUser.py in get_json(self)
     44         try:
---> 45             return extract_user_profile(scripts[4])
     46         except (json.decoder.JSONDecodeError, KeyError):

7 frames
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/instagramy/InstagramUser.py in extract_user_profile(script)
     16     data = script.contents[0]
     17     info = json.loads(data[data.find('{"config"') : -1])
---> 18     return info["entry_data"]["ProfilePage"][0]["graphql"]["user"]
     19 
     20 

KeyError: 'ProfilePage'

**Comment by yogeshwaran01** [comment]
@NivedhaRamesh Try this on your Local Python Interpreter. This Package not work in Remote pc or any online python Interpreter.

**Comment by kareemrasheed89** [comment]
> facing error on running the following query:
> 
> "from instagramy import InstagramUser user = InstagramUser("github") user.number_of_followers"
> 
> Error:
> 
> JSONDecodeError Traceback (most recent call last) /usr/local/lib/python3.6/dist-packages/instagramy/InstagramUser.py in get_json(self) 44 try: ---> 45 return extract_user_profile(scripts[4]) 46 except (json.decoder.JSONDecodeError, KeyError):
> 
> 7 frames JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 
> During handling of the above exception, another exception occurred:
> 
> KeyError Traceback (most recent call last) /usr/local/lib/python3.6/dist-packages/instagramy/InstagramUser.py in extract_user_profile(script) 16 data = script.contents[0] 17 info = json.loads(data[data.find('{"config"') : -1]) ---> 18 return info["entry_data"]["ProfilePage"][0]["graphql"]["user"] 19 20
> 
> KeyError: 'ProfilePage'

Ensure you have session_id added to your instatiation of InstragramUser.... Check the ReadMe from this page to get sessionid
