### ISSUE TITLE
Impossible to use it

### ISSUE THREAD

**Issue by Louis-Allard** [yogeshwaran01/instagramy#4]
```
Traceback (most recent call last):
  File "rs_i.py", line 6, in <module>
    user = InstagramUser('github')
  File "/home/phenx/.local/lib/python3.8/site-packages/instagramy/InstagramUser.py", line 32, in __init__
    if check_username(username):
  File "/home/phenx/.local/lib/python3.8/site-packages/instagramy/InstagramChecks.py", line 26, in check_username
    token = response.cookies["csrftoken"]
  File "/usr/lib/python3/dist-packages/requests/cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "/usr/lib/python3/dist-packages/requests/cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"
```

**Comment by yogeshwaran01** [comment]
It works perfectly on local PC

![Screenshot from 2020-12-03 23-12-50](https://user-images.githubusercontent.com/66836092/101067349-756b7600-35bd-11eb-8b53-a6730ad69704.png)

**Comment by Louis-Allard** [comment]
i tried with another pc, it's doesn't work also, witth the same message as the other one. Maybe something missed ?

**Comment by yogeshwaran01** [comment]
@Louis-Allard yes, You're right the code not working since today morning. Instagram does not allow to Scarpe the content.
I think this package became useless. You try to change something on code.

**Comment by Louis-Allard** [comment]
i tried to scrap insta using beatifulsoup, nothing work...

**Comment by yogeshwaran01** [comment]
@Louis-Allard Now I changed the code and bugs get fixed. Now It works perfectly fine in my local. 
Update the package `pip install instagramy --upgrade` before you try it. 
But there are some [limitation](https://github.com/yogeshwaran01/instagramy#note).  please try to find some solutions.

**Comment by Louis-Allard** [comment]
thx u

**Comment by chsaiujwal** [comment]
Today morning I tried, getting same error...

**Comment by yogeshwaran01** [comment]
@chsaiujwal 

Update the package by `pip install --upgrade instagramy `

[Read it Once](https://github.com/yogeshwaran01/instagramy#note)

**Comment by chsaiujwal** [comment]
Thanks a lot, it's working.
