### ISSUE TITLE
pip install instagramy not working

### ISSUE THREAD

**Issue by AbimbolaObadare** [yogeshwaran01/instagramy#5]
pip install instagramy
Collecting instagramy
  Using cached https://files.pythonhosted.org/packages/01/4c/5376dd3567e7b31af3d8fd996ee181c9e0d77373d9970114a0c18054042c/instagramy-3.7.tar.gz
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\user\Anaconda3\envs\env\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-hjnkteis\\instagramy\\setup.py'"'"'; __file__='"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-hjnkteis\\instagramy\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: C:\Users\user\AppData\Local\Temp\pip-install-hjnkteis\instagramy\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\user\AppData\Local\Temp\pip-install-hjnkteis\instagramy\setup.py", line 4, in <module>
        long_description = fh.read()
      File "C:\Users\user\Anaconda3\envs\env\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 3018: character maps to <undefined>
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by yogeshwaran01** [comment]
@AbimbolaObadare  Check your python version >= 3.8.5

You can try following commands:
```bash
pip install git+https://github.com/yogeshwaran01/instagramy.git
```
(or)

```bash
git clone https://github.com/yogeshwaran01/instagramy

python setup.py install
```

**Comment by AbimbolaObadare** [comment]
Thank you for your response.
